name: Build and Release Executables

on:
  push:
    tags:
      - v*  # 当推送带有v前缀的标签时触发工作流
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            extension: ""
          - os: windows-latest
            extension: .exe

    steps:
      # 检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v2
      
      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # 您需要的Python版本

      # 安装依赖项（如果有）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 安装 PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 打包为可执行文件
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --strip --clean per_station_data.py

      # 上传生成的二进制文件为GitHub的artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable-${{ matrix.os }}
          path: ./dist/per_station_data${{ matrix.extension }}


  release:
    needs: build  # 确保 release job 在 build job 完成后运行
    runs-on: ubuntu-latest
    steps:
      # 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release  # 设置一个ID，以便后续步骤引用
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # GitHub 提供的身份验证令牌
        with:
          tag_name: ${{ github.ref }}  # 使用推送的标签作为发布的版本号
          release_name: Release ${{ github.ref }}  # 发布的名称
          draft: false
          prerelease: false

      # 上传 Linux 版本到 Release
      - name: Upload Linux asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 获取前一个步骤中创建的 release 的 upload_url
          asset_path: ./dist/per_station_data
          asset_name: per_station_data-linux
          asset_content_type: application/octet-stream

      # 上传 Windows 版本到 Release
      - name: Upload Windows asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 获取 upload_url
          asset_path: ./dist/per_station_data.exe
          asset_name: per_station_data-windows.exe
          asset_content_type: application/octet-stream